name: "laptop_debug"

trainer:
  output_path: "./exp/laptop"
  max_steps: 30000
  val_interval: 5000
  training: True
  pose_free:
    debug: True
    geo_steps: 2000
    motion_steps: 3000
    init_q_lr: 1e-2
    end_q_lr: 1e-5
    init_t_lr: 1e-2
    end_t_lr: 1e-5
    color_steps: 10000
    k_clusters: 128

  model:
    name: VidArtModel
    lambda_ssim: 0.2
    point_cloud:
      point_cloud_type: "GaussianPointCloud"  
      max_sh_degree: 3
      trainable: true
      unwarp_prefix: "point_cloud"
      initializer:
        init_type: 'custom'
        feat_dim: 3
        num_points: 5000
        radius: 1.0
    camera_model:
      name: "CameraModel"
      enable_training: False
    renderer:
      name: "MsplatOrthoRender"
      max_sh_degree: ${trainer.model.point_cloud.max_sh_degree}
    loss_coef:
      depth: 1
      opa: 2

  controller:
    normalize_grad: False
    # min_opacity: 0.1
    # duplicate_interval: 200
    # prune_interval: 200

  optimizer:
    optimizer_1:
      type: BaseOptimizer
      name: Adam
      args:
        eps: 1e-15
      extra_cfg:
        backward: False
      params:
        point_cloud.position:
          lr: 0.00016
        point_cloud.features:
          lr: 0.0025
        point_cloud.features_rest:
          lr: 0.000125 # features/20
        point_cloud.scaling:
          lr: 0.005
        point_cloud.rotation:
          lr: 0.001
        point_cloud.opacity:
          lr: 0.05
      # camera_params:
      #   lr: 1e-3
  
  scheduler:
    name: "ExponLRScheduler"
    params:
      point_cloud.position:
        init:  0.00016
        final: 0.0000016
        max_steps: ${trainer.pose_free.geo_steps}
  datapipeline:
    data_set: "ColmapDepthNormalDataset"
    shuffle: False
    batch_size: 1
    num_workers: 0
    dataset:
      data_path: "./examples/vid_art_GS"
      seq_name: "laptop_10211"
      cached_observed_data: ${trainer.training}
      scale: 0.25
      white_bg: False
      observed_data_dirs_dict: {"image": "images", "normal": "normals"}
      num_imgs: 250
      base_idx: 0

  writer:
    writer_type: "TensorboardWriter"
  
  hooks:
    LogHook:
      name: ArtVidLogHook
    CheckPointHook:
      name: CheckPointHook
  
  exporter:
    exporter_a:
      type: MetricExporter
    exporter_b:
      type: TSDFFusion
      extra_cfg:
        voxel_size: 0.02
        sdf_truc: 0.08
        total_points: 8_000_000
    exporter_c:
      type: VideoExporter